import Header from './components/Header';
import './global.scss';

export const metadata = {
  title: 'Welcome to no',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="page-wrapper">
          <Header></Header>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
