import { Header } from 'components/server';
import './global.scss';

export const metadata = {
  title: 'Welcome to no',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const links = [
    {
      title: 'Home',
      url: '/'
    },
    {
      title: 'Productos',
      url: '/products'
    }
  ]
  return (
    <html lang="en">
      <body>
        <div className="page-wrapper">
          <Header links={links}/>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
